### ISSUE TITLE
xDAQ cannot find boost libraries on Debian

### ISSUE THREAD

**Issue by lmoureaux** [lpetre-ulb/gemsuperbuild#5]
(On branch `feature/archlinux`)

On Debian, `boost` libraries are installed in `/usr/lib/x86_64-linux-gnu/` and not `/usr/lib/`. Moreover, they don't use the `-mt` suffix and several versions can be installed in parallel. The patch xDAQ should be configured according to the results of `FindBoost`.

**Comment by lpetre-ulb** [comment]
Indeed, the `-mt` suffix for `boost_thread` has been removed in the recent distribution. It is fixed in the patch for Archlinux. Is there other `boost` libraries with issues on Debian ? How are the different versions managed by Debian ?

Regarding the path, I'm a bit surprised that it is not in the default search directories of `ld`. Could you please post the result of this command : `ld --verbose | grep SEARCH_DIR` ?

On Archlinux it gives :
``` bash
[lpetre-ulb@ ~]$ ld --verbose | grep SEARCH_DIR
SEARCH_DIR("/usr/x86_64-pc-linux-gnu/lib64"); SEARCH_DIR("/usr/lib"); SEARCH_DIR("/usr/local/lib"); SEARCH_DIR("/usr/x86_64-pc-linux-gnu/lib");
```

If the issue cannot fixed fixed in an other way, sure, a patch configured by `FindBoost` could be the solution.

**Comment by lmoureaux** [comment]
Works if xDAQ is patched correctly.
